# Generated by Django 4.1.5 on 2023-03-02 00:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mapod4d',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=21, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('description', models.TextField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Mapod4dVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(default='')),
                ('v1', models.PositiveIntegerField(default=0)),
                ('v2', models.PositiveIntegerField(default=0)),
                ('v3', models.PositiveIntegerField(default=0)),
                ('v4', models.PositiveIntegerField(default=0)),
                ('p', models.CharField(default='s', max_length=2)),
                ('bricks', models.PositiveIntegerField(default=1)),
                ('compress', models.BooleanField(default=False)),
                ('value', models.PositiveIntegerField()),
                ('mapod4d', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapod4d.mapod4d')),
            ],
        ),
        migrations.AddConstraint(
            model_name='mapod4dversion',
            constraint=models.UniqueConstraint(models.F('v1'), models.F('v2'), models.F('v3'), models.F('v4'), name='mapod4d_version'),
        ),
    ]
