# Generated by Django 4.1.5 on 2023-04-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapod4d', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='mapod4dversion',
            name='mapod4d_version',
        ),
        migrations.AddConstraint(
            model_name='mapod4dversion',
            constraint=models.UniqueConstraint(models.F('mapod4d'), models.F('v1'), models.F('v2'), models.F('v3'), models.F('v4'), name='mapod4d_version'),
        ),
    ]
