# Generated by Django 4.1.5 on 2023-04-19 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapod4d', '0002_remove_mapod4dversion_mapod4d_version_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapod4dversion',
            name='value',
        ),
    ]
