# Generated by Django 4.1.5 on 2023-04-21 18:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapod4d', '0003_remove_mapod4dversion_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapod4dversion',
            name='v1',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AlterField(
            model_name='mapod4dversion',
            name='v2',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AlterField(
            model_name='mapod4dversion',
            name='v3',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AlterField(
            model_name='mapod4dversion',
            name='v4',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999)]),
        ),
    ]
