# Generated by Django 4.1.5 on 2023-04-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapod4d', '0004_alter_mapod4dversion_v1_alter_mapod4dversion_v2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapod4dversion',
            name='test',
            field=models.CharField(default='s', max_length=200),
        ),
    ]
