# Generated by Django 4.1.5 on 2023-04-22 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapod4d', '0006_remove_mapod4dversion_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapod4dversion',
            name='compress',
        ),
        migrations.AddField(
            model_name='mapod4dversion',
            name='compressed',
            field=models.BooleanField(default=True),
        ),
    ]
