# Generated by Django 4.1.5 on 2023-01-11 10:34

import django.core.validators
from django.db import migrations, models
import multiverse.models


class Migration(migrations.Migration):

    dependencies = [
        ('multiverse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metaverse',
            name='description',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='metaverse',
            name='link',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='metaverse',
            name='mapod4d_id',
            field=models.CharField(default='a a', max_length=50, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')]),
        ),
    ]
