# Generated by Django 4.1.5 on 2023-01-11 10:34

import django.core.validators
from django.db import migrations, models
import multiverse.models

def mapod4d_id_default(apps, schema_editor):
    Metaverse = apps.get_model('multiverse', 'Metaverse')
    for row in Metaverse.objects.all():
        now = daterime.now()
        if rou.mapod4d_id == 'a a':
            row.mapod4d_id = now.strftime('%H%M%S%f')
        row.save(update_fields=['mapod4d_id'])

class Migration(migrations.Migration):

    dependencies = [
        ('multiverse', '0002_metaverse_description_metaverse_link_and_more'),
    ]

    operations = [
        migrations.RunPython(mapod4d_id_default)
    ]
