# Generated by Django 4.1.5 on 2023-01-11 10:34

import django.core.validators
from django.db import migrations, models
import multiverse.models


class Migration(migrations.Migration):

    dependencies = [
        ('multiverse', '0003_metaverse_description_metaverse_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metaverse',
            name='mapod4d_id',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')]),
        ),
    ]
