# Generated by Django 4.1.5 on 2023-02-23 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiverse', '0007_alter_metaverse_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='metaverse',
            name='bricks',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='metaverse',
            name='compress',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='metaverse',
            name='frommv1',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='metaverse',
            name='frommv2',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='metaverse',
            name='frommv3',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='metaverse',
            name='frommv4',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='metaverse',
            name='tomv1',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='metaverse',
            name='tomv2',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='metaverse',
            name='tomv3',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='metaverse',
            name='tomv4',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='metaverse',
            name='v1',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='metaverse',
            name='v2',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='metaverse',
            name='v3',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='metaverse',
            name='v4',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
