# Generated by Django 4.1.5 on 2023-02-23 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multiverse', '0008_metaverse_bricks_metaverse_compress_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metaverse',
            name='bricks',
        ),
        migrations.RemoveField(
            model_name='metaverse',
            name='compress',
        ),
        migrations.RemoveField(
            model_name='metaverse',
            name='frommv1',
        ),
        migrations.RemoveField(
            model_name='metaverse',
            name='frommv2',
        ),
        migrations.RemoveField(
            model_name='metaverse',
            name='frommv3',
        ),
        migrations.RemoveField(
            model_name='metaverse',
            name='frommv4',
        ),
        migrations.RemoveField(
            model_name='metaverse',
            name='link',
        ),
        migrations.RemoveField(
            model_name='metaverse',
            name='tomv1',
        ),
        migrations.RemoveField(
            model_name='metaverse',
            name='tomv2',
        ),
        migrations.RemoveField(
            model_name='metaverse',
            name='tomv3',
        ),
        migrations.RemoveField(
            model_name='metaverse',
            name='tomv4',
        ),
        migrations.RemoveField(
            model_name='metaverse',
            name='v1',
        ),
        migrations.RemoveField(
            model_name='metaverse',
            name='v2',
        ),
        migrations.RemoveField(
            model_name='metaverse',
            name='v3',
        ),
        migrations.RemoveField(
            model_name='metaverse',
            name='v4',
        ),
        migrations.CreateModel(
            name='MetaverseVersions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(default='')),
                ('v1', models.PositiveIntegerField(default=0)),
                ('v2', models.PositiveIntegerField(default=0)),
                ('v3', models.PositiveIntegerField(default=0)),
                ('v4', models.PositiveIntegerField(default=0)),
                ('bricks', models.PositiveIntegerField(default=1)),
                ('compress', models.BooleanField(default=False)),
                ('frommv1', models.PositiveIntegerField(default=0)),
                ('frommv2', models.PositiveIntegerField(default=0)),
                ('frommv3', models.PositiveIntegerField(default=0)),
                ('frommv4', models.PositiveIntegerField(default=0)),
                ('tomv1', models.PositiveIntegerField(default=0)),
                ('tomv2', models.PositiveIntegerField(default=0)),
                ('tomv3', models.PositiveIntegerField(default=0)),
                ('tomv4', models.PositiveIntegerField(default=0)),
                ('metaverse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multiverse.metaverse')),
            ],
        ),
    ]
