# Generated by Django 4.1.5 on 2023-02-23 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multiverse', '0009_remove_metaverse_bricks_remove_metaverse_compress_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MetaverseVersions',
            new_name='MetaverseVersion',
        ),
    ]
