# Generated by Django 4.1.5 on 2023-02-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiverse', '0010_rename_metaverseversions_metaverseversion'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='metaverseversion',
            constraint=models.UniqueConstraint(models.F('metaverse'), models.F('frommv1'), models.F('frommv2'), models.F('frommv3'), models.F('frommv4'), models.F('tomv1'), models.F('tomv2'), models.F('tomv3'), models.F('tomv4'), name='unique_range_mapod4d'),
        ),
        migrations.AddConstraint(
            model_name='metaverseversion',
            constraint=models.UniqueConstraint(models.F('metaverse'), models.F('frommv1'), models.F('frommv2'), models.F('frommv3'), models.F('frommv4'), name='unique_fromv_mapod4d'),
        ),
        migrations.AddConstraint(
            model_name='metaverseversion',
            constraint=models.UniqueConstraint(models.F('metaverse'), models.F('tomv1'), models.F('tomv2'), models.F('tomv3'), models.F('tomv4'), name='unique_to'),
        ),
    ]
