# Generated by Django 4.1.5 on 2023-03-04 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_users'),
        ('multiverse', '0012_remove_metaverseversion_unique_range_mapod4d_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metaverse',
            name='multiverse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='multiverse_metaverses', to='multiverse.multiverse'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='metaverse',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_metaverses', to='projects.project'),
        ),
    ]
