# Generated by Django 4.1.5 on 2023-04-19 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiverse', '0013_metaverse_multiverse_alter_metaverse_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='metaverseversion',
            name='p',
            field=models.CharField(default='s', max_length=2),
        ),
        migrations.AddConstraint(
            model_name='metaverseversion',
            constraint=models.UniqueConstraint(models.F('metaverse'), models.F('v1'), models.F('v2'), models.F('v3'), models.F('v4'), name='metaverse_version'),
        ),
    ]
