# Generated by Django 4.1.5 on 2023-04-22 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multiverse', '0015_alter_metaverseversion_v1_alter_metaverseversion_v2_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='metaverseversion',
            name='metaverse_version_range',
        ),
        migrations.RemoveConstraint(
            model_name='metaverseversion',
            name='metaverse_version_fromver',
        ),
        migrations.RemoveConstraint(
            model_name='metaverseversion',
            name='metaverse_version_tover',
        ),
    ]
