# Generated by Django 4.1.5 on 2023-01-21 14:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('link', models.URLField(default='')),
                ('v1', models.PositiveIntegerField(default=0)),
                ('v2', models.PositiveIntegerField(default=0)),
                ('v3', models.PositiveIntegerField(default=0)),
                ('v4', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(default='', max_length=200)),
            ],
        ),
    ]
