# Generated by Django 4.1.5 on 2023-02-22 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softwares', '0003_alter_software_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='bricks',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='software',
            name='compress',
            field=models.BooleanField(default=False),
        ),
    ]
