# Generated by Django 4.1.5 on 2023-04-22 19:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softwares', '0004_software_bricks_software_compress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='software',
            old_name='compress',
            new_name='compressed',
        ),
        migrations.AlterField(
            model_name='software',
            name='v1',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AlterField(
            model_name='software',
            name='v2',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AlterField(
            model_name='software',
            name='v3',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AlterField(
            model_name='software',
            name='v4',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AddConstraint(
            model_name='software',
            constraint=models.UniqueConstraint(models.F('name'), models.F('v1'), models.F('v2'), models.F('v3'), models.F('v4'), name='software_version'),
        ),
    ]
