# Generated by Django 4.1.5 on 2023-04-22 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softwares', '0005_rename_compress_software_compressed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='compressed',
            field=models.BooleanField(default=True),
        ),
    ]
