# Generated by Django 4.1.5 on 2023-04-22 19:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softwares', '0006_alter_software_compressed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='name',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')]),
        ),
    ]
