# Generated by Django 4.1.5 on 2023-04-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softwares', '0008_software_so'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='software',
            name='software_version',
        ),
        migrations.AddConstraint(
            model_name='software',
            constraint=models.UniqueConstraint(models.F('name'), models.F('so'), models.F('v1'), models.F('v2'), models.F('v3'), models.F('v4'), name='software_version'),
        ),
    ]
