# Generated by Django 4.1.5 on 2023-04-23 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softwares', '0009_remove_software_software_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='so',
            field=models.CharField(choices=[('L00', 'Linux'), ('W00', 'MS Windows')], default='L00', max_length=3),
        ),
    ]
